name: Teste com Jest
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Teste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/expo-github-action@v6
        with:
          expo-version: 4.x
      - run: npm i
      - run: npm jest